name: Metrics
on:
  # Se actualiza cada 12 horas
  schedule: [{cron: "0 */12 * * *"}]
  # Permite ejecutarlo manualmente para probar
  workflow_dispatch:
  # Se ejecuta al hacer cambios en la rama principal
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generar Métricas
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Costa_Rica 
        
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          
          plugin_fortune: yes
